spring:
  application:
    name: slate

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


jwt:
  secret: ${JWT_SECRET}
  expiry-ms: ${JWT_EXPIRY_MS:900000}
  refresh-expiry-ms: ${JWT_REFRESH_EXPIRY_MS:2592000000}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

server:
  port: 8080
